### ISSUE TITLE
Service exporter - Invalid URL validation check

### ISSUE THREAD

**Issue by yemijaiyeola** [WeAreSnook/human-services#1]
**User Story**
High level story for the Service Exporter tool:
As a data custodian, I need to be able to export my data into a Google sheet, so that I can get an overview of all of the data in my service directory

Story for this ticket:
As a data custodian, if I paste an invalid URL into the Service Exporter, I need to get confirmation that it is invalid before the tool tries to start exporting, so that the app doesn't crash.

**Why is this important/What evidence do we have**
Basic quality, user experience for the Service Exporter, prevents app crash.

**What is the work**
We need to check on the server side if the URL is valid. If it is not valid, we return an error message.

**Acceptance Criteria**
As a user, if I paste an **invalid URL**, 
I receive an error message that asks me to enter a valid URL

Definition of invalid URL - a URL that can be accessed.
Example Invalid Test URLs:
- "fgggkgkt"
- "www.fjggkgkt.com"

**Comment by yemijaiyeola** [comment]
A validation check on the URL is required

**Comment by yemijaiyeola** [comment]
An invalid url currently will cause the application to crash

client side validation in place
Validate a 200 response from URL

**Comment by ailsaleen** [comment]
@ailsaleen add expected copy, maybe chat to Ananda/Ann about expected experience

**Comment by yemijaiyeola** [comment]
Pull request to address

https://github.com/WeAreSnook/human-services/pull/20

**Comment by yemijaiyeola** [comment]
Done
