### ISSUE TITLE
Update URLs as per Ann's suggestion

### ISSUE THREAD

**Issue by kingdomlevel** [WeAreSnook/human-services#100]
This will require (a small amount of) work in the front and back end:

Page | Current (in CMS) | Update urls to:
-- | -- | --
openreferraluk.org (stem) |   |  
Home | / | /
About Open Referral UK | /about-page | **/about-open-referral**
How it works | /how-to | /**how-it-works**
Community | /community | /community
Contact us | /contact-us | /contact-us
Documentation and tools | /docs-and-tools/ | **/documentation-and-tools**

**Comment by UsmanAfzal** [comment]
@kingdomlevel please find guidance on this within #87.

**Comment by PorismDominicSkinner** [comment]
Done.
