### ISSUE TITLE
Add additional non conforming elements of the website to accessibility statement

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/human-services#114]

**Comment by UsmanAfzal** [comment]
@annhelen Please find the accessibility statement ready for final review.

[Final Accessibility Statement](https://docs.google.com/document/d/1iTHud59rr1naYmvGnlrcxoubwyjB6bpXpzKJHdwosng/edit?usp=sharing)

**Comment by annhelen** [comment]
Thanks @UsmanAfzal - I've proofread it and all looks good.
@ailsaleen Just to note this will need uploading into CMS.

**Comment by PorismDominicSkinner** [comment]
Done
