### ISSUE TITLE
Front end page - content page: article

### ISSUE THREAD

**Issue by anandamaryon** [WeAreSnook/human-services#124]
Figma link: https://www.figma.com/proto/2xrZWgoxb0vgylFFbimESB/ORUK-page-designs?page-id=0%3A1&node-id=1%3A280&viewport=-1264%2C1203%2C0.48452991247177124&scaling=min-zoom

Image for reference:
![Content page_ Article - mob](https://user-images.githubusercontent.com/76442772/115540068-9b0bca00-a295-11eb-95ce-5b609322d4a1.png)
![Content page_ Article](https://user-images.githubusercontent.com/76442772/115540075-9c3cf700-a295-11eb-8fa5-f264bb573b7d.png)

**Comment by kingdomlevel** [comment]
This has been implemented in a few places on the live site:
- [About page](https://beta.openreferraluk.org/about-open-referral)
- [Contact page](https://beta.openreferraluk.org/contact-us/)
- [Features of the standard](https://beta.openreferraluk.org/how-it-works/whats-in-the-standard)
- [Steps to adopt](https://beta.openreferraluk.org/how-it-works/step-by-step-guide-on-how-to-adopt-the-standard)
- [Individual case study page](https://beta.openreferraluk.org/community/case-studies/leeds-city-digital-partnerships)

.... it's worth noting that although there is a GenericContentPage component, only Features of the standard and steps to adopt are using that component for the implementation so far. The need to refactor has been noted in [issue #47 on the frontend repo](https://github.com/WeAreSnook/OR-UK-frontend/issues/47).

That being said - I think we should call this done for now...? If it's required to log the issue from the frontend repo in this repo as part of the github project then I'm happy to log it!
