### ISSUE TITLE
Service Exporter - Non-valid Directory URL check

### ISSUE THREAD

**Issue by ailsaleen** [WeAreSnook/human-services#14]
**User Story**
High level story for the Service Exporter tool:
As a data custodian, I need to be able to export my data into a Google sheet, so that I can get an overview of all of the data in my service directory

Story for this ticket:
As a data custodian, if I paste a link to something that isn't a service directory into the Service Exporter, I need to get confirmation that it is invalid, so that the app doesn't crash.

**Why is this important/What evidence do we have**
Basic quality, user experience for the Service Exporter, prevents app crash.

**What is the work**
When pagination returns 0 pages, we will be able to surface this information.

**Acceptance Criteria**
As a user, if I paste a link to a non-valid directory,
the Google sheet tells me that no service directory was found at this URL.

Example of valid URL that isn't a directory:
"https://www.facebook.com"

**Comment by ailsaleen** [comment]
@ailsaleen add expected copy, maybe chat to Ananda about expected experience

**Comment by yemijaiyeola** [comment]
https://github.com/WeAreSnook/human-services/pull/20

**Comment by ailsaleen** [comment]
medium priority (website is high priority)

**Comment by yemijaiyeola** [comment]
Done
