### ISSUE TITLE
Implement CMS - Strapi

### ISSUE THREAD

**Issue by HarryPotia** [WeAreSnook/human-services#15]
**User story**
High level story for the website: As a user, I need to find clear, information about Open Referral UK online, so that I can understand whether I should adopt the standard.

This specific story doesn't deliver end user value on its own but is needed in order to enable the ORUK website

**Why is it important**
The Open Referral UK website needs.
This is a high priority as it is one of the building blocks/foundations of the website.

**What is involved**
Choosing the CMS for the Open Referral UK website
_What are the factors involved in this choice?_

**Acceptance Criteria/Definition of Done**
A CMS is selected and the whole team is aligned and able to start setting up the CMS & hosting.

**Comment by yemijaiyeola** [comment]
Spike: 
Configuring AWS for CMS
Ensure any prerequisites needed for running CMS are installed and configured
Agreed backend I believe is MySql - but liaise with Dom

**Comment by yemijaiyeola** [comment]
> **User story**
> High level story for the website: As a user, I need to find clear, information about Open Referral UK online, so that I can understand whether I should adopt the standard.
> 
> This specific story doesn't deliver end user value on its own but is needed in order to enable the ORUK website
> 
> **Why is it important**
> The Open Referral UK website needs.
> This is a high priority as it is one of the building blocks/foundations of the website.
> 
> **What is involved**
> Choosing the CMS for the Open Referral UK website
> _What are the factors involved in this choice?_

> 
> **Acceptance Criteria/Definition of Done**
> A CMS is selected and the whole team is aligned and able to start setting up the CMS & hosting.



> **User story**
> High level story for the website: As a user, I need to find clear, information about Open Referral UK online, so that I can understand whether I should adopt the standard.
> 
> This specific story doesn't deliver end user value on its own but is needed in order to enable the ORUK website
> 
> **Why is it important**
> The Open Referral UK website needs.
> This is a high priority as it is one of the building blocks/foundations of the website.
> 
> **What is involved**
> Choosing the CMS for the Open Referral UK website
> _**What are the factors involved in this choice?_**
> 
@anandamaryon please review the list and  add any additional requirements
- one where the component parts (back-end, frontend, API) are independent and customisable. 
- allows us to seamlessly target content at a wide range of devices
- allow us to build a custom API for accessing content
- Allows us a flexible choice of content repository (database)
- Flexible hosting choice
-  Preferably JavaScript based
-  one that is open source
- Widely adopted and with a community around it


> **Acceptance Criteria/Definition of Done**
> A CMS is selected and the whole team is aligned and able to start setting up the CMS & hosting.

@ailsaleen thank you for doing this.  I was just going to review and write a use case for this.

**Comment by anandamaryon** [comment]
I'd just add that the CMS needs to integrate or somehow enable a forum or knowledge base solution.

**Comment by yemijaiyeola** [comment]
> I'd just add that the CMS needs to integrate or somehow enable a forum or knowledge base solution.

Noted. Thanks

**Comment by kingdomlevel** [comment]
We had a meeting about this today (Thurs 25/03) and the general consensus seems to be that we will progress with Strapi (pending a discussion with Ann (content) in the next few days).

We have agreed on a few next steps to look at in the mean time:

- [ ] Investigate content-editor / author role + permissions. Set up a demo user.
- [ ] Look into the WYSIWYG editor in strapi.. I think it offers integration w [CKEditor5](https://ckeditor.com/ckeditor-5/demo/)
- [ ] Have a look at the [Strapi preview content plugin](https://github.com/danestves/strapi-plugin-preview-content) (shared by Harry - thanks!)
