### ISSUE TITLE
Implement hosting platform for CMS and dev tools

### ISSUE THREAD

**Issue by HarryPotia** [WeAreSnook/human-services#16]
**User story**
High level story for the website: As a user, I need to find clear, information about Open Referral UK online, so that I can understand whether I should adopt the standard.

This specific story doesn't deliver end user value on its own but is needed in order to enable the ORUK website

**Why is it important**
This is a high priority as it is one of the building blocks/foundations of the website.

**What is involved**
Agreeing a hosting platform for the Open Referral UK website

**Acceptance Criteria/Definition of Done**
A hosting platform is selected and the whole team is aligned and able to start setting up the CMS & hosting.

**Comment by PorismDominicSkinner** [comment]
I have set up the dot net core tools in Linux here are the URL's:

https://validator.openreferraluk.org/
https://exporter.openreferraluk.org/

Note that as the exporter is now at a different URL this will need to be updated in the OAuth consent screen: #8
