### ISSUE TITLE
Choose & upload Terms of Service & Privacy Policy

### ISSUE THREAD

**Issue by ailsaleen** [WeAreSnook/human-services#80]
needed for https://github.com/WeAreSnook/human-services/issues/8

as well as for general website needs

**Comment by MikeThacker1** [comment]
The content for these is in:

Por11060 - ORUK Privacy notice https://docs.google.com/document/d/157ibInrA7KZ7F4YnAGZdOVspE8goo1Cw4prm9-L4zC0/edit?usp=sharing
Por11061 - ORUK Terms and Conditions https://docs.google.com/document/d/1EAdwjw81qcOSbHiZ52zV3pvbefXy5xZjDg96MVVV4Os/edit?usp=sharing

**Comment by kingdomlevel** [comment]
Uploaded the following privacy policy + terms of service to the CMS:
- [Por11060 - ORUK Privacy notice](https://docs.google.com/document/d/157ibInrA7KZ7F4YnAGZdOVspE8goo1Cw4prm9-L4zC0/edit?usp=sharing)
- [Por11061 - ORUK Terms and Conditions](https://docs.google.com/document/d/1EAdwjw81qcOSbHiZ52zV3pvbefXy5xZjDg96MVVV4Os/edit?usp=sharing)

At this stage, there may still be comments on the doc (e.g some links) that need addressing
